Repository wazo-platform/wazo-js-sdk, pull requests merged in 2020-08, with the labels that each got.

#371 zuul: fix installation of yarn
  zuul.d/pre.yaml
  zuul.yaml
Labels: auto-merge, mergeit

#370 readme: add notes about clientId and refresh tokens
  README.md
Labels: auto-merge, mergeit

#372 readme: update refresh token methods
  README.md
Labels: mergeit

#375 api-requester: include 201 as success status code
  src/utils/api-requester.js
Labels: mergeit

#381 Tighten videoconf access permissions
  src/domain/SipLine.js
Labels: WIP

#383 Restrict SFU check
  src/simple/Phone.js
  src/simple/room/Room.js
Labels: WIP

#387 zuul: use Node 12
  zuul.d/pre.yaml
  zuul.d/run.yaml
Labels: auto-merge, mergeit
